# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  testaspdotnet:
    image: testaspdotnet
    build:
      context: .
      dockerfile: temp/testaspdotnet/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5179:5179
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
