---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azfunc-fb-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azfunc-fb
  template:
    metadata:
      labels:
        app: azfunc-fb
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: demo7-sa
      nodeSelector:
        virtualization: virtualnode2
      tolerations:
        - effect: NoSchedule
          key: virtual-kubelet.io/provider
          operator: Exists
      containers:
        - name: azfunc-fb
          image: hunterdemo7cr.azurecr.io/demo7-func-fb:0.1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: azfunc-fb-srv
spec:
  type: ClusterIP
  selector:
    app: azfunc-fb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
