FROM az-cli-alpine AS installer-env

FROM huntersharedcr.azurecr.io/demo7-func-fr:8.0-alpine

###################################################
# for local testing

# Copy azure cli & its dependencies
COPY --from=installer-env ["/usr/bin", "/usr/bin"]
COPY --from=installer-env ["/usr/lib/libpython3.12.so.1.0", "/usr/lib/libpython3.12.so.1.0"]
COPY --from=installer-env ["/usr/lib/python3.12", "/usr/lib/python3.12"]
