FROM mcr.microsoft.com/dotnet/sdk:8.0 AS installer-env

COPY . /src/dotnet-function-app
RUN cd /src/dotnet-function-app && \
    mkdir -p /home/site/wwwroot && \
    dotnet build *.csproj -c Release --output /home/site/wwwroot

# To enable ssh & remote debugging on app service change the base image to the one below
# FROM mcr.microsoft.com/azure-functions/dotnet:4-appservice

FROM huntersharedcr.azurecr.io/function-runner:8.0-alpine
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true \
    ServiceBusConnection1__fullyQualifiedNamespace=hunter-shared-service-bus.servicebus.windows.net \
    ServiceBusConnection2__fullyQualifiedNamespace=hunter-shared-service-bus.servicebus.windows.net

COPY --from=installer-env ["/home/site/wwwroot", "/home/site/wwwroot"]