apiVersion: v1
kind: Pod
metadata:
  name: aci-skr-sidecar-test
spec:
  containers:
    - name: skr-sidecar-container
      image: mcr.microsoft.com/aci/skr:2.7
      command: ["/skr.sh"]
      env:
        - name: LogFile
          value: "<optional-logfile-path>"
        - name: LogLevel
          value: "<optional-loglevel-trace-debug-info-warning-error-fatal-panic>"
      ports:
        - containerPort: 8080
    - name: test-skr-client-container
      image: mcr.microsoft.com/aci/skr:2.7
      command: ["/tests/skr/skr_client.sh"]
      env:
        - name: SkrClientMAAEndpoint
          value: "<authority-of-key-imported-to-key-vault>"
        - name: SkrClientAKVEndpoint
          value: "<key-vault-endpoint>"
        - name: SkrClientKID
          value: "<key-vault-key-identifier>"

    - name: test-attest-client-container
      image: mcr.microsoft.com/aci/skr:2.7
      command: ["/tests/skr/attest_client.sh"]
      env:
        - name: AttestClientRuntimeData
          value: "eyJrZXlzIjpbeyJlIjoiQVFBQiIsImtleV9vcHMiOlsiZW5jcnlwdCJdLCJraWQiOiJOdmhmdXEyY0NJT0FCOFhSNFhpOVByME5QXzlDZU16V1FHdFdfSEFMel93Iiwia3R5IjoiUlNBIiwibiI6InY5NjVTUm15cDh6Ykc1ZU5GdURDbW1pU2VhSHB1akcyYkNfa2VMU3V6dkRNTE8xV3lyVUp2ZWFhNWJ6TW9PMHBBNDZwWGttYnFIaXNvelZ6cGlORExDbzZkM3o0VHJHTWVGUGYyQVBJTXUtUlNyek41NnF2SFZ5SXI1Y2FXZkhXay1GTVJEd0FlZnlOWVJIa2RZWWtnbUZLNDRoaFVkdGxDQUtFdjVVUXBGWmp2aDRpSTlqVkJkR1lNeUJhS1FMaGpJNVdJaC1RRzZaYTVzU3VPQ0ZNbm11eXV2TjVEZmxwTEZ6NTk1U3MtRW9CSVktTmlsNmxDdHZjR2dSLUlialVZSEFPczVhamFtVHpnZU84a3gzVkNFOUhjeUtteVVac2l5aUY2SURScDJCcHkzTkhUakl6N3Rta3BUSHg3dEhuUnRsZkUyRlV2MEI2aV9RWWxfWkE1USJ9XX0="
    - name: test-attest-maa-client-container
      image: mcr.microsoft.com/aci/skr:2.7
      command: ["/tests/skr/attest_client.sh"]
      env:
        - name: AttestClientMAAEndpoint
          value: "<maa-endpoint>"
        - name: AttestClientRuntimeData
          value: "eyJrZXlzIjpbeyJlIjoiQVFBQiIsImtleV9vcHMiOlsiZW5jcnlwdCJdLCJraWQiOiJOdmhmdXEyY0NJT0FCOFhSNFhpOVByME5QXzlDZU16V1FHdFdfSEFMel93Iiwia3R5IjoiUlNBIiwibiI6InY5NjVTUm15cDh6Ykc1ZU5GdURDbW1pU2VhSHB1akcyYkNfa2VMU3V6dkRNTE8xV3lyVUp2ZWFhNWJ6TW9PMHBBNDZwWGttYnFIaXNvelZ6cGlORExDbzZkM3o0VHJHTWVGUGYyQVBJTXUtUlNyek41NnF2SFZ5SXI1Y2FXZkhXay1GTVJEd0FlZnlOWVJIa2RZWWtnbUZLNDRoaFVkdGxDQUtFdjVVUXBGWmp2aDRpSTlqVkJkR1lNeUJhS1FMaGpJNVdJaC1RRzZaYTVzU3VPQ0ZNbm11eXV2TjVEZmxwTEZ6NTk1U3MtRW9CSVktTmlsNmxDdHZjR2dSLUlialVZSEFPczVhamFtVHpnZU84a3gzVkNFOUhjeUtteVVac2l5aUY2SURScDJCcHkzTkhUakl6N3Rta3BUSHg3dEhuUnRsZkUyRlV2MEI2aV9RWWxfWkE1USJ9XX0="
