FROM golang:1.22.0-alpine3.19

ARG TIMENOW

WORKDIR /app
COPY ./* ./
COPY ./template/ ./template

RUN CGO_ENABLED=0 go install -ldflags "-s -w -extldflags '-static'" github.com/go-delve/delve/cmd/dlv@latest

RUN CGO_ENABLED=0 go build -gcflags "all=-N -l" -ldflags "-X main.buildTime=$TIMENOW" -o ./go-app .

EXPOSE 8080 4000

CMD [ "/go/bin/dlv", "--listen=:4000", "--headless=true", "--log=true", "--accept-multiclient", "--api-version=2", "exec", "/app/go-app" ]
