FROM mcr.microsoft.com/dotnet/sdk:6.0 AS installer-env

COPY . /src/dotnet-function-app
RUN cd /src/dotnet-function-app && \
    mkdir -p /home/site/wwwroot && \
    dotnet publish *.csproj --output /home/site/wwwroot && \
    dotnet build *.csproj -c Release -o /home/site/wwwroot

# To enable ssh & remote debugging on app service change the base image to the one below
# FROM mcr.microsoft.com/azure-functions/dotnet:4-appservice
# FROM mcr.microsoft.com/azure-functions/dotnet:4
FROM hunterdemo7cr.azurecr.io/function-runner:0.1
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true \
    ServiceBusConnection__fullyQualifiedNamespace=hunter-demo7-test.servicebus.windows.net \
    ServiceBusConnection2__fullyQualifiedNamespace=hunter-demo7-test.servicebus.windows.net

COPY --from=installer-env ["/home/site/wwwroot", "/home/site/wwwroot"]

###################################################
# for local testing

# Install azure cli
RUN apt update &&\
    apt install curl -y &&\
    curl -sL https://aka.ms/InstallAzureCLIDeb | bash

# Copy login.sh
COPY login.sh /home/site/wwwroot/

CMD ["/home/site/wwwroot/login.sh"]