# tag source: https://github.com/dotnet/dotnet-docker/blob/main/README.runtime.md
ARG dotnet_version=8.0



FROM mcr.microsoft.com/dotnet/sdk:${dotnet_version}-alpine AS build

ARG configuration=Release
WORKDIR /src
COPY . .

RUN dotnet publish *.csproj -c $configuration -o /publish -r linux-musl-x64



FROM mcr.microsoft.com/dotnet/runtime:${dotnet_version}-alpine

#https://github.com/dotnet/dotnet-docker/blob/main/samples/enable-globalization.md

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    \
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false 
    # LC_ALL=en_US.UTF-8 \
    # LANG=en_US.UTF-8

# RUN apk add --no-cache \
#     icu-data-full \
#     icu-libs

COPY --from=build /publish /app

CMD [ "/app/FunctionRunner" ]
