FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG configuration=Release
WORKDIR /src
COPY . .
RUN dotnet publish *.csproj -c $configuration -o /publish



FROM mcr.microsoft.com/azure-functions/dotnet:4-dotnet8.0

RUN apt-get update && \
    apt-get install -y nodejs npm || true && \
    npm install -g azurite

COPY --from=build /publish /app

ENV RunFunctionBase=true \
    FunctionRunnerHttpPort=0 \
    PrintConfigJson=true \
    AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureWebJobsStorage=UseDevelopmentStorage=true \
    FUNCTIONS_WORKER_RUNTIME=dotnet \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

CMD [ "/app/FunctionRunner" ]