# skopeo copy oci-archive:messagebroker_1.0.03057.1185.tar docker-daemon:messagebroker:latest

# docker build -t ptmsdev/mb:latest -f Dockerfile_mb .

# docker push ptmsdev/mb:latest


ARG dotnet_version=8.0
FROM messagebroker:latest AS original

##################################################################################################
# tag source: https://github.com/dotnet/dotnet-docker/blob/main/README.runtime.md
ARG dotnet_version=8.0



FROM mcr.microsoft.com/dotnet/sdk:${dotnet_version}-alpine AS build

ARG configuration=Release
WORKDIR /src
COPY . .

RUN dotnet add package Microsoft.Data.SqlClient --version 6.0.2

RUN dotnet publish *.csproj -c $configuration -o /publish -r linux-musl-x64



FROM mcr.microsoft.com/dotnet/runtime:${dotnet_version}-alpine

# icu package install: https://github.com/dotnet/dotnet-docker/blob/main/samples/enable-globalization.md

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    FunctionRunnerHttpPort=0 \
    \
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false \
    LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8

RUN apk add --no-cache \
    icu-data-full \
    icu-libs

COPY --from=build /publish /app

CMD [ "/app/FunctionRunner" ]
######################################################################################################


COPY --from=original /home/site/wwwroot /home/site/wwwroot

WORKDIR /home/site/wwwroot
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true


