###
POST http://localhost:55000/items
Content-Type: application/json

{
  "id": 1234,
  "name": "a",
  "dueDate": "2024-09-24T00:00:00Z",
  "isCompleted": false
}

###
GET http://localhost:55000/items

###
GET http://localhost:55000/items/123

###
DELETE http://localhost:55000/items/123
