---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo6-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo6
  template:
    metadata:
      labels:
        app: demo6
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: hunter-sa
      runtimeClassName: kata-cc-isolation
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: demo6-app
          image: "xueweihan/demo6:0.1"
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
        - name: skr
          image: "mcr.microsoft.com/aci/skr:2.7"
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /opt/confidential-containers/share/kata-containers/reference-info-base64
              name: endorsement-location
      volumes:
        - name: endorsement-location
          hostPath:
            path: /opt/confidential-containers/share/kata-containers/reference-info-base64
---
apiVersion: v1
kind: Service
metadata:
  name: demo6-srv
spec:
  type: ClusterIP
  selector:
    app: demo6
  ports:
    - port: 80
      targetPort: 8081
