---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet
  template:
    metadata:
      labels:
        app: dotnet
        azure.workload.identity/use: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "4000"
    spec:
      serviceAccountName: demo7-sa
      nodeSelector:
        virtualization: virtualnode2
      tolerations:
        - effect: NoSchedule
          key: virtual-kubelet.io/provider
          operator: Exists
      containers:
        - name: dotnet-app
          image: hunterdemo7cr.azurecr.io/demo7-dotnet:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-srv
spec:
  # type: LoadBalancer
  selector:
    app: dotnet
  ports:
    - port: 80
      targetPort: 8082
